/*FIRST LET'S JUST GET EVERYTHING THAT CAN GO TO THE INGREDIENT LEVEL TO THE INGREDIENT LEVEL*/
/*SINCE IT IS SLOW, WE'LL WRITE IT TO A TEMP TABLE*/
/*REMEMBER A CLINICAL DRUG THAT IS A COMBO DRUG WILL DUPILICATE THE EVIDENCE ACROSS THE COMBINATIONS, WE CANNOT ASSUME WHICH INGREDIENT SHOULD TAKE THE BLAME*/
SELECT r.HOI AS CONDITION_CONCEPT_ID, r.SNOMED_HOI AS CONDITION_CONCEPT_NAME,
	r.DRUG AS DRUG_CONCEPT_ID, r.RXNORM_DRUG AS DRUG_CONCEPT_NAME,  
	c.CONCEPT_ID AS INGREDIENT_ID, c.CONCEPT_NAME AS INGREDIENT_NAME,
	CASE WHEN c.CONCEPT_ID IS NULL THEN 0 ELSE 1 END INGREDIENT_EXISTS, 
	c2.CONCEPT_ID AS CLINICAL_DRUG_ID,c2.CONCEPT_NAME AS CLINICAL_DRUG_NAME,
	CASE WHEN c2.CONCEPT_ID IS NULL THEN 0 ELSE 1 END CLINICAL_DRUG_EXISTS, 
	e.EVIDENCE_TYPE, e.SUPPORTS, e.EVIDENCE_SOURCE_CODE_ID, e.STATISTIC_VALUE, e.EVIDENCE_LINKOUT, e.STATISTIC_TYPE
INTO TEMP TABLE TEMP_DRUG_HOI_EVIDENCE_W_INGREDIENTS
FROM DRUG_HOI_EVIDENCE e
	JOIN DRUG_HOI_RELATIONSHIP r
		ON r.ID = e.DRUG_HOI_RELATIONSHIP
	/*ROLL DOWN TO INGREDIENTS*/
	LEFT OUTER JOIN CONCEPT_ANCESTOR ca
		ON ca.DESCENDANT_CONCEPT_ID = r.DRUG
		AND ca.ANCESTOR_CONCEPT_ID IN (
			SELECT DISTINCT CONCEPT_ID
			FROM CONCEPT
			WHERE VOCABULARY_ID = 'RxNorm'
			AND CONCEPT_CLASS_ID = 'Ingredient'
			AND INVALID_REASON IS NULL
		)
	LEFT OUTER JOIN CONCEPT c
		ON c.CONCEPT_ID = ca.ANCESTOR_CONCEPT_ID
	/*ROLL UP TO CLINICAL DRUG*/
	LEFT OUTER JOIN CONCEPT_ANCESTOR ca2
		ON ca2.DESCENDANT_CONCEPT_ID = r.DRUG
		AND ca2.ANCESTOR_CONCEPT_ID IN (
			SELECT DISTINCT CONCEPT_ID
			FROM CONCEPT
			WHERE VOCABULARY_ID = 'RxNorm'
			AND CONCEPT_CLASS_ID = 'Clinical Drug'
			AND INVALID_REASON IS NULL
		)
	LEFT OUTER JOIN CONCEPT c2
		ON c2.CONCEPT_ID = ca2.ANCESTOR_CONCEPT_ID;

/*NOW THAT WE HAVE THAT TABLE, LET'S FILTER TO ONLY THE CONDITIONS IN THE HOIs OF INTEREST*/
WITH CTE_HOI AS ( 
	SELECT DISTINCT c.CONCEPT_ID AS HOI_CONCEPT_ID, c.CONCEPT_NAME AS HOI_CONCEPT_NAME, 
		c1.CONCEPT_ID AS CONDITION_CONCEPT_ID, c1.CONCEPT_NAME AS CONDITION_CONCEPT_NAME 
	FROM CONCEPT c JOIN CONCEPT_ANCESTOR ca 
		ON ca.ANCESTOR_CONCEPT_ID = c.CONCEPT_ID 
	JOIN CONCEPT c1 
		ON c1.CONCEPT_ID = ca.DESCENDANT_CONCEPT_ID 
		AND c1.INVALID_REASON IS NULL 
	WHERE c.CONCEPT_ID IN (500000301)

	--( /*YOU NEED TO DOUBLE CHECK THAT THESE ARE ALL THE OMOP HOI CONCEPT IDS*/
	--	500000402,500000404,500000801,500001003,500000308,500000303,500000802,500000805,500000301,500000403,500000405,500000401,500000302,500000305,500001001,500000307,500000803,500000306,500000304 
	--) 
)
SELECT h.HOI_CONCEPT_ID, h.HOI_CONCEPT_NAME, i.*
FROM TEMP_DRUG_HOI_EVIDENCE_W_INGREDIENTS i
	JOIN CTE_HOI h
		ON h.CONDITION_CONCEPT_ID = i.CONDITION_CONCEPT_ID
WHERE SUPPORTS = 'false'
ORDER BY HOI_CONCEPT_ID, CONDITION_CONCEPT_NAME, DRUG_CONCEPT_NAME, INGREDIENT_NAME, EVIDENCE_TYPE
